### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by zhajjhassan** [imbus/robotframework-PlatynUI#1]
- [ ] Keywords für RFW schreiben (Kann unabhängig von der Lib gemacht werden)
- [ ]  PythonLibCore - Basis für unsere Lib (Abstraction library)
- [x]  AssertionEngine
- [x]  Erstellung von keywords in Python (direkt mit Library verbunden) Bsp. ButtonKeywords.py, TextKeywords.py
- [ ] Einbinden der Klassen in der init- Funktion   (super().__init__([ButtonKeywords(), TextKeywords()....)
- [ ] Möglichkeit zum Starten der Anwendung (andere Lib ? eigene schreiben, RDP lib)
- [ ] Testen in einer UI (welche? isbpn launcher?)
- [ ] WPF App in die Repo hochladen (@d-biehl )
- [x] Spy App in die Repo hochladen

**Links:**
[AssertionEngine](https://github.com/MarketSquare/AssertionEngine)
[PythonLibCore](https://github.com/robotframework/PythonLibCore)
[RPA-Desktop](https://robocorp.com/docs/libraries/rpa-framework/rpa-desktop)
